### ISSUE TITLE
Menumeters still not working in Catalina

### ISSUE THREAD

**Issue by objjg** [yujitach/MenuMeters#119]
It worked until I rebooted, then I'm back to beachballs and hung System Preferences.

Honestly I'm so sick of Catalina I'm ready to dump it. 
I used to have a desktop clock.. no longer works.
Menumeters no longer works. 
I have to go to root to configure Catalina the way I want. 
The few new features are not worth the BS I've had to put up with.

**Comment by yujitach** [comment]
The problem of MenuMeters on Catalina is that Catalina doesn’t like (or care about) non-Apple preference panes within System Preferences. I decided to move out of the pref pane.

Could you try the preliminary new version https://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/zips/MenuMeters_1.9.9.zip ? 

It runs outside of System Preferences. (Unfortunately, once downloaded, you *need* to move it to some folder other than the originally downloaded place, so that the app auto-updates itself when new versions appear. This is a step required by Apple for all downloaded app, starting from Sierra. )

**Comment by yujitach** [comment]
Please make further comments on #113 .
