### ISSUE TITLE
Alignment of texts

### ISSUE THREAD

**Issue by yujitach** [yujitach/MenuMeters#15]
I was asked, by an email, to fix a minor issue on the alignment of numerals inside the menu bar.

![screen shot 2015-10-06 at 2 54 44 pm](https://cloud.githubusercontent.com/assets/5449811/10447725/e1e59fce-71c1-11e5-9488-fb161b7f9f8b.png)

I don't know if I'd like to fix it right now, but let me keep the info publicly here.

**Comment by mackonsti** [comment]
Due to the new El Capitan system font, I think that a small fix is definitely needed.

What I would like to suggest and contribute, perhaps, is to improve:
a) AquaLights icons (disk activity) that need some polishing
and
b) reduce the thermometer outline of the CPU (it's too white and in dark mode it is not nice).

Finally the fonts on the network interface should be moved to Bold, as the new system font is too thin and on my MacBook (non-retina) I cannot very clearly see them. Please let me know if I can help!

**Comment by yujitach** [comment]
Thanks for the suggestion.  As I've heard that the original author of MenuMeters is considering his own full port to El Capitan, I'm not sure if I'm very much interested in improving MM on my side. I guess I should ask him if he would also do the development on GitHub so that anybody can collaborate. In the meantime, you can always fork the repo and work on it; the pull request is always welcome.

**Comment by mackonsti** [comment]
Hi yujitach and thank you for keeping the interest for MenuMeters alive. I am not sure the original author has still made any announcement about supporting it further, please kindly let us know if you have such news, perhaps he can take advantage of the public interest of MM and continue work here?

In any case, let us know about slightly enhancing further the UI as it's been very long time since it was done :-)

**Comment by yujitach** [comment]
I finally tried to make things better.  I agree with b) and implemented it. a) is #38 . The text is now aligned OK on Catalina but Big Sur seems to have made further changes to the menu bar font style and it is again off. Ugh. I tentatively close this issue though.

**Comment by mackonsti** [comment]
Thanks @yujitach for your changes and work, looking forward to trying out the next stable build. Cheers.

**Comment by yujitach** [comment]
I’m not sure if my latest change would be to your liking, let’s see...
