### ISSUE TITLE
Showing Wrong Version in 2.0.5

### ISSUE THREAD

**Issue by GerardDirks** [yujitach/MenuMeters#156]
Hallo

I update Version 2.0.4 to 2.0.5!

When I click on "check for updated" it displays me "You'r up-to-date" Menumeters 2.0.5 is currently the newest version available"
But in the Finder Info it still showing 2.0.4, also in the about Menu is no comment for Version about  2.0.5 and what is new!

**Comment by yujitach** [comment]
@GerardDirks 
Thanks for the comments, but please do understand that it's a free software I maintain using my spare time. I can't guarantee anything. 

The version number issue was already fixed in #154 by @luckman212 , but I won't release a new update just to fix this, as I know many users of MenuMeters don't like mini updates fixing mini issues.

I removed your comments concerning the color and the automatic update, as they are covered under different issues #145 and #134, respectively.

**Comment by yujitach** [comment]
It’s fixed in the latest release.
