### ISSUE TITLE
Network meter don't show the RX values

### ISSUE THREAD

**Issue by AhmedKorim** [yujitach/MenuMeters#173]
Thanks for this great project,
I was using MenuMeters on Mojave it worked as expected,
After a clean installation for macOS Catalina, Meter doesn't show the Download rate (always 0),
IDK if this is a driver issue or MenuMeters' issue
![image](https://user-images.githubusercontent.com/35463181/89518453-c4c8a380-d78f-11ea-8b3d-fe170021c855.png)

**Comment by yujitach** [comment]
It seems to happen with some interface driver. Could you tell us which Mac and which interface do you use? Also, we've received reports that the bug went away by installing the latest Catalina version. Which version of Catalina do you use?

This is a bug being discussed in #143 . It would be nice if you could comment on that thread, instead of doing that here.
