### ISSUE TITLE
The latest version (2.0.8.1) doesn't work on Mojave 10.14.6

### ISSUE THREAD

**Issue by ForceBru** [yujitach/MenuMeters#188]
I recently got a popup from MenuMeters saying that an update was available (version 2.0.8.1), so I installed it - and MenuMeters completely disappeared from the status bar. I can see that the process is running, but nothing shows up. I tried moving the app to Trash and manually installing from GitHub - nothing changed: the MenuMeters process is running, but the status bar item is still gone.

The site says that Mojave users may face issues, but I remember updating to some previous version via the same update popup - and everything still worked afterwards.

-------

* macOS Mojave 10.14.6
* MenuMeters 2.0.8.1

**Comment by yujitach** [comment]
Thanks and I'm sorry for the problem. But I'm really puzzled by the behavior. I don't see any problem on my Catalina machine and my Big Sur machine. The issue #185 says the preference window fails to show on Catalina too... 

I'd like to ask you two things:

- what happens if you reinstall 2.0.7? (It's available in the "releases".

- what happens if you create a new account on your Mac and install 2.0.8.1?

**Comment by ForceBru** [comment]
Thanks for the quick response!

* 2.0.7 works fine
* 2.0.8.1 works fine in the new account, but doesn't work for the main account

**Comment by yujitach** [comment]
Thanks. Is it that you set the menubar to auto-hide? It appears your issue is the same one as #185 = #189. For this I released an update https://github.com/yujitach/MenuMeters/releases/tag/2.0.8.2 . Please tell me if it fixes your issue too.

**Comment by ForceBru** [comment]
Indeed, the menu bar is set to auto-hide. 2.0.8.3 works, thank you!

**Comment by yujitach** [comment]
Thanks for reporting and checking.
