### ISSUE TITLE
Big Sur menu bar color + dynamic wallpaper

### ISSUE THREAD

**Issue by kirtan** [yujitach/MenuMeters#195]
In Big Sur, the menu bar icon color changes based on your wallpaper color. When using a dynamic wallpaper, this results in MenuMeters being the wrong color sometimes.

<img width="255" alt="Screen Shot 2020-11-17 at 11 06 25 PM" src="https://user-images.githubusercontent.com/271440/99407224-cfb3d800-2929-11eb-9485-1c2e1fdd7f97.png">

Would be great to sync the colors to current menu bar (white/black)

**Comment by Jasonsey** [comment]
I have the same issue

**Comment by yujitach** [comment]
Do you set the color to be completely black?

**Comment by kirtan** [comment]
Yes black or white. But when the wallpaper changes, the rest of the icons change (white/black flip) except menumeters

**Comment by yujitach** [comment]
Is my understanding correct that you encounter the same issue if you manually change the desktop picture so that the menu bar changes from the light mode to the dark mode?

**Comment by kirtan** [comment]
Yes, or if you select a dynamic wallpaper that changes from light to dark

**Comment by Hopper262** [comment]
On my machine with 11.0.1, I'm not seeing this issue on any MenuMeters items except the Memory Usage Bar border (and possibly Usage Chart too). There, the "pure black/white" color tint sets the border to black on a light background, but the border is dark gray instead of white on a dark background. The CPU vertical bars, by contrast, behave exactly as I'd expect and change from black to white appropriately.

**Comment by yujitach** [comment]
@Hopper262 thanks for reporting that. It's fixed in the latest commit, although I don't know when it'll be available in a public release...

**Comment by yujitach** [comment]
@kirtan Another person pointed out the same issue with a concrete suggestion how to resolve it in #204 . I will merge the two issues, keeping #204 .
