### ISSUE TITLE
Preference file soft links overwritten

### ISSUE THREAD

**Issue by mascguy** [yujitach/MenuMeters#209]
If soft links are used for the MenuMeters preference files, they are handled properly when the app loads. However, when any preferences are changed, those links are overwritten by new preference files.

**Comment by yujitach** [comment]
Which of the two preference files, `com.yujitach.MenuMeters.plist` and `com.ragingmenace.MenuMeters.plist`, poses the problem for you? Or maybe both?

Also, does the same soft-link trick work with other apps you use?

I'm using the standard API for `com.yujitach.MenuMeters.plist`, so there's nothing I can do with it.

The other file `com.ragingmenace.MenuMeters.plist` is carried over from the code the original author provided, and uses somewhat uncommon APIs. So that might be causing the problem. But I believe there are other apps which use the same API as this one, posing the same problem with you.

**Comment by mascguy** [comment]
So far, it's only the `com.ragingmenace.MenuMeters.plist` file. So perhaps it's the old code?

But yes, I use soft-linked preference files for a wide variety of apps -- both open-source, and commercial -- and it works in all cases.

**Comment by yujitach** [comment]
Ah, I see. That makes sense. The old `MenuMeters` was split into a pref pane within `System Preferences` and menu extras loaded within `SystemUIServer`. In order to communicate the preferences between the two parts, `MenuMeters` therefore used Carbon APIs which allows direct specification of the `.plist` file to operate on. I think that is what is causing the problem here. 

I've been modernizing the internals of `MenuMeters` recently (albeit very slowly), and the code around the preference manipulations is one of the places where the code rot is significant. But I'm not sure if I can find the time to deal with this issue in the near future.

**Comment by mascguy** [comment]
Would you accept a pull request with the fix?

**Comment by yujitach** [comment]
That would be nice. There are two steps. First, migrate the content of `com.ragingmenace.MenuMeters.plist` to `com.yujitach.MenuMeters.plist`. Then, rewrite the code accessing the old plist so that it uses the new plist. More concretely,

- Add a code in `AppDelegate` which runs only once to copy the content of `com.rangingmenace.MenuMeters.plist` into `[NSUserDefaults standardUserDefaults]`

- Replace all occurrences of `CFPreference...` calls accessing `com.ragingmenace.MenuMeters` with `NSDefaults` calls using `standardUserDefaults` in `MenuMeterDefaults.m`

Good luck. I promise that the code in `MenuMeterDefaults.m` is a mess.

**Comment by mascguy** [comment]
No worries, this sounds like a great challenge. Thanks you so much!

**Comment by yujitach** [comment]
Hi, I found the time so I fixed it.
