### ISSUE TITLE
Memory and network meters have disappeared in 2.1.2

### ISSUE THREAD

**Issue by bconway** [yujitach/MenuMeters#210]
Just updated from 2.1.1 to 2.1.2 on a relatively fresh install of Catalina, and my memory and network meters have disappeared. Toggling them on and off in the preferences has no effect. Preferences shows no changes in settings.

Thanks.

**Comment by yujitach** [comment]
Thanks for the report. I remove the release from the auto-update again for the moment. Please download 2.1.1 from https://github.com/yujitach/MenuMeters/releases/tag/2.1.1 in the meantime. Let me see what’s wrong... as it works fine on my Catalina machine...

**Comment by bconway** [comment]
Thanks. I switched back to 2.1.1 and functionality is as expected.

**Comment by yujitach** [comment]
Did the CPU meter work on 2.1.2?

**Comment by bconway** [comment]
Yes, CPU and disk worked as expected.

**Comment by yujitach** [comment]
What is the main language you set in System Preferences.app ? Probably it's other than English...

**Comment by yujitach** [comment]
I was checking the code diff between 2.1.1 and 2.1.2 but I don't immediately see where the problem lies. As it works here on my Catalina machine it's very difficult to fix for me.

As you seem to be a programmer, could you try running MenuMeters within Xcode to see what's wrong? My hunch is that somehow an exception is raised within -[AppDelegate init] at
https://github.com/yujitach/MenuMeters/blob/91cd706fd76b8590db04cc496b98b9b24bbc2fbe/MenuMetersApp/AppDelegate.m#L91
when it tries to init the net meter . Then the mem meter is not even initialized due to the uncaught exception.

**Comment by bconway** [comment]
Thank you for jumping on this so quickly. It looks like you've already figured it out, but for next time:

- English language, US-based.
- I don't have Xcode installed (and am not likely to have it), but I'd be happy to gather logs or console/terminal output in the future.

Thanks.

**Comment by yujitach** [comment]
Thank you for reporting the bug so quickly. It helps a lot of other users. I think I already fixed it, but could you test the attached binary (2.1.2.1) to see if it really works?
[MenuMeters_2.1.2.1.zip](https://github.com/yujitach/MenuMeters/files/5682561/MenuMeters_2.1.2.1.zip)

**Comment by bconway** [comment]
Works great, thank you.

![Screen Shot 2020-12-12 at 9 00 14 AM](https://user-images.githubusercontent.com/630723/101987245-7d2fb800-3c58-11eb-935b-ae70b140d35e.png)

**Comment by yujitach** [comment]
Thanks for the confirmation!
