### ISSUE TITLE
Feature Request: Show CPU Temperature in CPU menu

### ISSUE THREAD

**Issue by Impakt** [yujitach/MenuMeters#45]
I noticed that the CPU temperature is part of the CPU usage bar graph, but I thought it would be nice to include it in the CPU dropdown menu where it shows Threads/Load Average, etc.

**Comment by yujitach** [comment]
As far as I understand, the "Thermometer" feature is just a thermometer-like plot of the current activity of the CPU, and not actually the temperature of the CPU. MenuMeters had the feature to show the temperature in the long gone past, though. 

As always you're welcome to provide a patch so that I can merge it.

**Comment by yujitach** [comment]
This is implemented in this fork: https://gitlab.com/axet/MenuMeters

**Comment by Splaktar** [comment]
The fork has some issues, like not being able to hide the custom date menu and no updates for Mojave/dark mode. It would be nice to add temp readings like in the fork to this project.

Thank you for your work!
