### ISSUE TITLE
Duplicate charts showing after reinstall

### ISSUE THREAD

**Issue by IBMRob** [yujitach/MenuMeters#68]
I've reinstalled the latest version into high sierra and I see that all charts are duplicated.

Below is what my menu looks like if I have Network enabled
![image](https://user-images.githubusercontent.com/2182970/32326951-af7bbcde-bfcc-11e7-96bf-d59c8e1ed2df.png)
or network and memory
![image](https://user-images.githubusercontent.com/2182970/32326962-b7ebbc8e-bfcc-11e7-8d1e-35239cf6ea88.png)

When I tick enable one of the meters it appear instantly and then a second later the second instance appears.

Mac OS 10:13
MenuMeters v1.9.6

**Comment by sandhub** [comment]
@RobQuads, you should try to uninstall completely by right clicking on MenuMeters in System Preferences and then emptying trash. A reboot is also required. Once it is completely uninstalled, try installing again. This worked for me when I had the same issue. 🙏

**Comment by yujitach** [comment]
Since v2.0.5, MenuMeters automatically kills every older instances of MenuMeters. (In fact this feature is done in a bit too aggressive manner, so that if you have two installations of the same version, there's a race condition that each tries to kill the other at the same time and both are killed, resulting in no MenuMeters running. I think this actually happening to be rather unlikely, unless you develop MenuMeters locally. So I haven't tried to code in a more resilient way.)
