### ISSUE TITLE
Bug: Network arrows' activity invisible in dark mode

### ISSUE THREAD

**Issue by jtb1234** [yujitach/MenuMeters#90]
Is there a way to make the network arrows dark when there is activity? Not just the borders of the arrows the whole arrow. When using dark mode it doesn't show any activity.

**Comment by robindevouge** [comment]
Hi! 
If you use any other colour than black for transmit and receive in dark mode, arrows become visible again. That's because arrows' borders are the colour you chose and their fill opacity varies depending the activity, thus black over black isn't visible (you can still see them on a non focused desktop's menu bar if you use multiple screens because unfocused bars are dark grey instead of black).
And if I understand what your issue is, you could try using a dark grey?

Hope this helps

**Comment by yujitach** [comment]
It's basically the same issue with #204 . The point is that it is reasonable to set the color either to
- system default color (black when light mode, white when dark mode), or 
- the color of your choice .

Merging it.
